FROM mysql:5.7

ADD mysql/my.cnf /etc/mysql/my.cnf
ADD mysql/ca-cert.pem /etc/mysql-ssl/ca-cert.pem
ADD mysql/server-cert.pem /etc/mysql-ssl/server-cert.pem
ADD mysql/server-key.pem /etc/mysql-ssl/server-key.pem

RUN chown -R mysql:root /etc/mysql-ssl/*.pem

RUN chmod 600 /etc/mysql-ssl/*.pem
